"""D11S deterministic certification records and evidence hashing."""

from mind_runtime.validation.composition import (
    CanonicalCertificationComposition,
    CertificationRuntimeConfig,
    DurablePaths,
    build_composition,
)
from mind_runtime.validation.contracts import (
    DECODER_REGISTRY,
    REQUIRED_COMPONENT_IDS,
    ArtifactManifest,
    CertificationPlan,
    CertificationReport,
    CheckpointPolicyConfig,
    ContextRendererConfig,
    DailyDecisionDigest,
    DecisionAuthoritySnapshot,
    DecodedRuntimeConfig,
    DurableStoreModes,
    EffectiveStateConfig,
    FactIngestConfig,
    HistoricalContextConfig,
    HistoryFixture,
    HomeostasisConfig,
    HorizonTemplate,
    InputArtifactRef,
    IntentEngineConfig,
    IntentLifecycleConfig,
    InvariantResult,
    ModelSwapFixture,
    PreviousExpressionConfig,
    ReceiptRegistryConfig,
    RestartFixture,
    RuntimeComponentConfig,
    RuntimeConfigManifest,
    SemanticProviderConfig,
    SimulationEvent,
    decode_component,
    decode_runtime_config_manifest_bytes,
    decode_runtime_manifest,
    load_history_fixture,
    load_horizon_template,
    load_model_swap_fixture,
    load_restart_fixture,
    load_runtime_config_manifest,
    verify_fixture_artifacts,
)
from mind_runtime.validation.digest import artifact_manifest, canonical_json_bytes, sha256_bytes
from mind_runtime.validation.history_audit import (
    DecisionInfluence,
    HistoryAuditResult,
    audit_repeated_history,
    derive_expected_history_effect,
)
from mind_runtime.validation.horizon import HorizonDayCapture, HorizonRun, HorizonRunner
from mind_runtime.validation.invariants import (
    CapturedContribution,
    FalseHistoryInvariantResult,
    HistoryStepCapture,
    LongHorizonCertification,
    certify_horizon,
    check_boundedness,
    check_false_history_reversible,
    check_no_self_excitation,
    check_registered_time_dynamics,
    check_replay,
    long_horizon_semantic_hash,
)
from mind_runtime.validation.model_swap import ModelSwapResult, compare_model_swap
from mind_runtime.validation.report import render_certification_summary, write_certification_report
from mind_runtime.validation.restart import RestartCertificationResult, certify_restart
from mind_runtime.validation.schedule import SimulationClock, ordered_events

__all__ = [
    "DECODER_REGISTRY",
    "REQUIRED_COMPONENT_IDS",
    "ArtifactManifest",
    "CertificationPlan",
    "CertificationReport",
    "CanonicalCertificationComposition",
    "CertificationRuntimeConfig",
    "CapturedContribution",
    "CheckpointPolicyConfig",
    "ContextRendererConfig",
    "DailyDecisionDigest",
    "DecodedRuntimeConfig",
    "DecisionAuthoritySnapshot",
    "DecisionInfluence",
    "DurableStoreModes",
    "DurablePaths",
    "EffectiveStateConfig",
    "FactIngestConfig",
    "HistoricalContextConfig",
    "HistoryAuditResult",
    "HistoryFixture",
    "HistoryStepCapture",
    "HomeostasisConfig",
    "HorizonDayCapture",
    "HorizonRun",
    "HorizonRunner",
    "HorizonTemplate",
    "InputArtifactRef",
    "IntentEngineConfig",
    "IntentLifecycleConfig",
    "InvariantResult",
    "FalseHistoryInvariantResult",
    "LongHorizonCertification",
    "ModelSwapFixture",
    "ModelSwapResult",
    "PreviousExpressionConfig",
    "ReceiptRegistryConfig",
    "RestartFixture",
    "RestartCertificationResult",
    "RuntimeComponentConfig",
    "RuntimeConfigManifest",
    "SemanticProviderConfig",
    "SimulationEvent",
    "SimulationClock",
    "artifact_manifest",
    "audit_repeated_history",
    "canonical_json_bytes",
    "build_composition",
    "certify_horizon",
    "certify_restart",
    "check_boundedness",
    "check_false_history_reversible",
    "check_no_self_excitation",
    "check_registered_time_dynamics",
    "check_replay",
    "compare_model_swap",
    "derive_expected_history_effect",
    "long_horizon_semantic_hash",
    "decode_component",
    "decode_runtime_manifest",
    "decode_runtime_config_manifest_bytes",
    "load_history_fixture",
    "load_horizon_template",
    "load_model_swap_fixture",
    "load_restart_fixture",
    "load_runtime_config_manifest",
    "ordered_events",
    "render_certification_summary",
    "sha256_bytes",
    "verify_fixture_artifacts",
    "write_certification_report",
]
